#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
ROOT=$(readlink --canonicalize "$HERE/../..")

"$ROOT/scripts/build"

cd "$HERE"

rm --force --recursive .terraform .terraform.lock.hcl *.tfstate*
terraform init
